[package]
name = "tester"
version = "0.1.0"
edition = "2024"

[dependencies]
maestro = { path = "../crates/maestro" }
finalflow-macros = { path = "../crates/proc-macros" }

[profile.dev]
incremental = false
