[package]
name = "finalflow"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
finalflow-macros = { path = "../proc-macros" }
eyre = "0.6.12"
rand = "0.9.1"
nix = { version = "0.30.1", features = ["process"] }
